controller_manager:
  ros__parameters:
    update_rate: 100

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

gripper_controller:
  ros__parameters:
    joint: gripper
    allow_stalling: true

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "gripper_frame_link"
    robot_base_link: "base_link"
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll

    # Choose: position or velocity.
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    solver:
        error_scale: 1.0
        iterations: 10

    pd_gains:
        trans_x: {p: 8.0}
        trans_y: {p: 8.0}
        trans_z: {p: 7.0}
        rot_x: {p: 10.0}
        rot_y: {p: 10.0}
        rot_z: {p: 10.0}